### ISSUE TITLE
EU 欧洲版 Hyper OS 刷入该模块提示“不兼容的品牌和设备”

### ISSUE THREAD

**Issue by CorryHsieh** [HuberHaYu/Mi-HyperOS-AudioIO#5]
EU 欧洲版 Hyper OS 刷入该模块失败，提示“不兼容的品牌和设备”。手机是红米K60（POCO F5 Pro），系统是欧洲版Hyper OS 1.0稳定版，Magisk 使用的是Kitsune Magisk 27001。

**Comment by HuberHaYu** [comment]
> EU 欧洲版 Hyper OS 刷入该模块失败，提示“不兼容的品牌和设备”。手机是红米K60（POCO F5 Pro），系统是欧洲版Hyper OS 1.0稳定版，Magisk 使用的是Kitsune Magisk 27001。

稍后会修复这个漏洞

**Comment by CorryHsieh** [comment]
> > EU 欧洲版 Hyper OS 刷入该模块失败，提示“不兼容的品牌和设备”。手机是红米K60（POCO F5 Pro），系统是欧洲版Hyper OS 1.0稳定版，Magisk 使用的是Kitsune Magisk 27001。
> 
> 稍后会修复这个漏洞

刷入最新的1.1版本仍然失败
[magisk_install_log_2024-10-16T22.53.16.log](https://github.com/user-attachments/files/17397719/magisk_install_log_2024-10-16T22.53.16.log)

**Comment by CorryHsieh** [comment]
1.2版本刷入成功，感谢修复。
